theme: jekyll-theme-midnight
title: Welcome to Irene's Homepage!!
description: Here is my lair for all my currently existing projects in the works.
![Image of mountains](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKe1Hzku4A4kKZ9Z03dW1eoV0Fl_IeD5X0Acto4GcBtAggQvPl)
